apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
        - name: webpage
          image: webpage:4.0
          imagePullPolicy: Never
          ports:
            - containerPort: 80
